### ISSUE TITLE
Does not properly add dburles:google-maps

### ISSUE THREAD

**Issue by pfafman** [jshimko/meteor-geocomplete#1]
If I set up dburles test project https://github.com/dburles/meteor-google-maps-demo and  do

```
meteor remove dburles:google-maps
meteor add jeremy:geocomplete
```

Then run it the project throws an error

```
ReferenceError: Can't find variable: GoogleMaps
```

Looking at your package.js file it seems ok but somehow the GoogleMaps object is not loading.

If I add in dburles:google-maps separately then it works.

**Comment by jshimko** [comment]
Hmm, interesting.  I can't reproduce that.  I downloaded that same example, removed his package and then added mine.  And...

```
$ meteor add jeremy:geocomplete

Changes to your project's package version selections:

dburles:google-maps  added, version 1.0.8
jeremy:geocomplete   added, version 1.6.4

jeremy:geocomplete: Geocoding and Google Places Autocomplete Plugin
```

**Comment by jshimko** [comment]
Oh weird... it doesn't appear to actually install the google-maps package.  

```
$ meteor list

autopublish         1.0.2  Publish the entire database to all clients
insecure            1.0.2  Allow all database writes by default
jeremy:geocomplete  1.6.4  Geocoding and Google Places Autocomplete Plugin
meteor-platform     1.2.1  Include a standard set of Meteor packages in your app
```

And I get the same console error.  Looks like the package system isn't doing it's job.

**Comment by jshimko** [comment]
I'm getting the same behavior with any package I try that has a dependency that isn't currently installed.  For example, I added a custom field type package for autoform and it says it installs autoform, simple-schema, etc., but none of them were actually added to the project.  Using an autoform helper throws an error.

Yikes.  This looks like a much larger problem.

**Comment by pfafman** [comment]
Well I guess we need to bump this up to the meteor guys.  Quick look does not see anything obvious in the issues for meteor.

**Comment by jshimko** [comment]
Apparently, this is expected behavior...

> It's expected behavior. In your application you can only use exported variables from packages you have explicitly added with `meteor add`. So run `meteor add aldeed:simple-schema` if you want to use SimpleSchema in your application.

https://github.com/meteor/meteor/issues/3829#issuecomment-76455876

**Comment by jshimko** [comment]
Ok, so there's a solution.  dburles:google-maps needs to be implied.  This has been fixed and you should no longer be able to reproduce the issue.

https://github.com/jshimko/meteor-geocomplete/blob/master/package.js#L17

Thanks for pointing it out!
