### ISSUE TITLE
Can't select places suggestions on mobile

### ISSUE THREAD

**Issue by EddyBorja** [jshimko/meteor-geocomplete#11]
I'm unable to select options from the Autocomplete list on mobile Safari. Every time I click on one the autocomplete disappears but the suggestion isn't placed into the input.

**Comment by jshimko** [comment]
Hmm.  I just tested my [example app](http://geocomplete.meteor.com/) with Safari on my iPhone 6 and didn't have any issues.  What version of iOS are you using?  Does it work with the [examples](https://github.com/ubilabs/geocomplete#examples) provided by the original plugin author? (non-meteor versions)

**Comment by EddyBorja** [comment]
It works in your example app and the original author's site. I removed the fastclick package thinking maybe that might be causing some kind of issue, but that didn't do anything either.  Using the latest iOS 8.3

**Comment by jshimko** [comment]
I'd be happy to take a look at your code if you have a public repo.

**Comment by EddyBorja** [comment]
Unfortunately I can't share the repo, but I tried my site on an Android phone's Chrome browser and it works there, so I can say it's specific to iOS (Safari and Chrome).

**Comment by jshimko** [comment]
But the issue only happens in your app, right?

**Comment by EddyBorja** [comment]
Yes

**Comment by jshimko** [comment]
Ok.  Sorry I can't help much then.  It's obviously tough to troubleshoot without being able to see it.  If you end up publishing a repo that reproduces the problem, I'll certainly give it a look.  Otherwise, good luck!  :)

**Comment by pcavadas** [comment]
I have the same issue, but only when I run the app as a cordova app on iOS. No problem on Android. And no problem as a website on Safari and Chrome on iOS.

I could reproduce the issue with the example app : https://github.com/jshimko/meteor-geocomplete-example
Simply create a `mobile-config.js`file with those lines:

``` javascript
App.accessRule('*.google.com/*');
App.accessRule('*.googleapis.com/*');
App.accessRule('*.gstatic.com/*');
```

Then run the app from the terminal:

``` bash
meteor add-platform ios
meteor run ios-device
```

**Comment by EddyBorja** [comment]
It's an issue with fastclick. I had to add this snippet

```
$(document).on({
                'DOMNodeInserted': function() {
                            $('.pac-item, .pac-item span', this).addClass('needsclick');
                                }
        }, '.pac-container');
```

I've read though this uses deprecated features or has poor performance.

**Comment by pcavadas** [comment]
It may not be the best solution, but it will do the trick for now. Thank you!
