### ISSUE TITLE
Trigger a resize event - map not rendering correctly 

### ISSUE THREAD

**Issue by isAlmogK** [jshimko/meteor-geocomplete#14]
When my map first loads it not rendering correctly, one of the ways to fix this is trigger a resize event 

![screen shot 2015-09-06 at 11 44 00 pm](https://cloud.githubusercontent.com/assets/169507/9706568/37efb460-54f1-11e5-8c65-e36987688efd.png)

I tried the following 
$("#location").geocomplete(map, "resize");
$("#location").geocomplete.maps.event.trigger(map, 'resize')

Is there a way to do this?

**Comment by jshimko** [comment]
Are you sure this has anything to do with geocomplete?  I've never run into the issue before.  Are you getting any console errors?

**Comment by isAlmogK** [comment]
No console errors, I had this issue before something to do with google maps and meteor. Something in blaze if you resize the browser window just a bit it's fine

**Comment by jshimko** [comment]
Hmm.  That's strange.  Every browser too?

**Comment by isAlmogK** [comment]
Only tested it on chrome, it's also possible that I have the map in the form wizard. My pervous app with this issue was a bootstrap modal, I just ran the resize event and it was fine more info here - http://stackoverflow.com/questions/27333535/google-map-not-working-in-bootstrap-modal

**Comment by isAlmogK** [comment]
I was able to fix this by moving the map init to helper function
