### ISSUE TITLE
Search for local businesses

### ISSUE THREAD

**Issue by gmlnchv** [jshimko/meteor-geocomplete#16]
Just trying to get my head around is to how this package is different to [lukemadera/meteor-autoform-googleplace](https://github.com/lukemadera/meteor-autoform-googleplace) in the sense that with lukemadera's package I'm able to get suggestions for local places (cafes and such) but not with meteor-geocomplete. Both packages load the same Places library but why different results?

**Comment by jshimko** [comment]
There's a lot of overlap, but each has a few unique features.  Autoform integration is one of the more obvious ones, of course.  That said, you're required to use Autoform with that package.  While this package doesn't come with Autoform integration, it's fairly trivial to set it up.  

In the end, it's really just simple text fields that are having their values populated automatically by a javascript plugin that calls an API.  So you'd just set up a normal text field input with Autoform like you would for any other `String` and then initialize this plugin on that input when the template renders.  When the form gets submitted, the value is grabbed from the input field by Autoform.

To see a concrete example, I did exactly the above for a [Telescope](http://www.telescopeapp.org/) theme a while back...

[Form Template](https://github.com/jshimko/telescope-datalook/blob/master/lib/client/views/d4g_post_submit_form.html#L24-L33)
(Note the two optional hidden text fields for lat/long.)

[Logic](https://github.com/jshimko/telescope-datalook/blob/master/lib/client/views/d4g_post_submit_form.js#L12-L25)
(Does the normal Geocomplete stuff and also populates the two hidden text fields with the lat/long once the location is chosen.)

[Schema](https://github.com/jshimko/telescope-datalook/blob/master/lib/collections.js#L67-L93) 
(You can ignore the Telescope-specific stuff in there.  Just need to define the `type`)

So maybe more importantly, you can take a look at the examples of Geocomplete usage [here](https://github.com/jshimko/meteor-geocomplete#examples).  Most of those aren't possible with the other plugin out of the box.

So it's not really a better/worse thing.  It just comes down to what you need and your preferences on how to get there.

**Comment by jshimko** [comment]
Sorry, forgot to answer the rest of the question...

You can take a look at the section on [Options](https://github.com/jshimko/meteor-geocomplete#list-of-options).  Specifically, see the [available options](https://developers.google.com/places/supported_types) for `types`.  

You can add any of those in your geocomplete config.

``` js
Template.myTemplate.onRendered(function() {
  this.autorun(function () {
    if (GoogleMaps.loaded()) {
      $("input").geocomplete({
        types: ['geocode', 'cafe', 'etc'] // default value is 'geocode'
      });
    }
  });
});
```

**Comment by gmlnchv** [comment]
Thanks so much for your answers, @jshimko! I think the `types` options is what I have been missing.

**Comment by xpluscal** [comment]
@jshimko : 
This is sort of relates / an identical question.
In README it says nothing about the field "name" of a place being returned.
Is it possible with the current Version?
