### ISSUE TITLE
Why wont the dropdown show

### ISSUE THREAD

**Issue by sferoze** [jshimko/meteor-geocomplete#19]
I have no idea why this is not working as your example. I just want a simple input box with autocomplete. It seems like it is loading google maps but no autocomplete dropdown is visible

`input(type='text')#us2-address`

```
t.autorun ->
    if GoogleMaps.loaded()
      t.$('#us2-address').geocomplete()
```

and I loaded google maps with places library and my API key. 

Why no dropdown?

**Comment by jshimko** [comment]
Not sure.  If you put together a reproduction repo, I'd be happy to take a look at it.

**Comment by sferoze** [comment]
Ahh I figured it out. 

When you put the input in a bootstrap modal the dropdown does not show because it shows up underneath the modal.

To fix this you have to add css to the dropdown container with `z-index 4000 !important` or something
