### ISSUE TITLE
detailsScope : not picking it up

### ISSUE THREAD

**Issue by slepit** [jshimko/meteor-geocomplete#21]
hello,

I tried to use the detailsScope option to have multiple forms on a single page but It still uses autofills the information (locality, latitude ...etc) on the first input fields it finds on the page.

I used id and name of a div in the detailedScope but it does not seem to pick it up

Do you have a sample (HTML and JS) on the usage of it ?

thanks

**Comment by jshimko** [comment]
I'm going to need more info to help you with that.  Can you provide some example code so I can see what you've tried?  Ideally, creating a basic reproduction repo would be the most helpful.  You can use [my Geocomplete example source](https://github.com/jshimko/meteor-geocomplete-example) as a starting point if that helps. 

Also, the [examples in the docs](https://github.com/jshimko/meteor-geocomplete#populate-form-data) work for me, so I suspect you're missing a small detail somewhere.

**Comment by slepit** [comment]
I think I miss used it or my client was not correctly refreshed..
