### ISSUE TITLE
using geocomplete upon 'modal'

### ISSUE THREAD

**Issue by asafshen** [jshimko/meteor-geocomplete#24]
Hi,
When I use geocomplete inside modals -  I can not see the text dropdown
(though i can navigate options with up\down keys..) 

`<template name="newSetupItemModal">
    <div id="modal-form-{{instance.modalName}}" class="modal fade" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                {{> quickForm id="formUpdate" schema="Schema.Test" collection="Test" type="insert" }}
...
`
Any suggestions?

Thanks.

**Comment by jshimko** [comment]
I'd need more info than that to make any suggestions.  If you post a sample repo reproducing the problem, I'd be happy to take a look.  You can use the Geocomplete example repo I published as a starting point if that helps...

https://github.com/jshimko/meteor-geocomplete-example

**Comment by asafshen** [comment]
Hi,

Thanks for the quick reply.
The package is really awesome.

I already found the solution
http://stackoverflow.com/questions/10957781/google-maps-autocomplete-result-in-bootstrap-modal-dialog
to my issue - only FYI:
- the autocomplete dropdown is not hidden if you use it inside modal (the
  modal is on top of it.)
- I used the CSS markup that was shown in the solution to override this..

Thanks a lot,
Asaf.

**Comment by jshimko** [comment]
:+1:

**Comment by acomito** [comment]
What is the class that needs to be targeted?

Neither of these are working for me:

```
.pac-container {
  z-index: 1051 !important;
}


.ui-autocomplete {
  z-index: 1051 !important;
}
```

also, this should probably be in the readme as it has come up several times

**Comment by asafshen** [comment]
hey @acomito 
my problem was occurred due to the bootstrap `modal` & `modal-backdrop` large z-index.

My solution:

```
.pac-container {
  background-color: #FFF;
  z-index: 5000;
  position: fixed;
  display: inline-block;
  float: left;
}
.modal {
  z-index: 20;
}
.modal-backdrop {
  z-index: 10;
}
```
- note that it is possible that in your case - the modal/modal-backdrop is not what causing the issue..
