### ISSUE TITLE
Dropdown doesnt work on ipad

### ISSUE THREAD

**Issue by braadworst** [jshimko/meteor-geocomplete#25]
When you click on one of the search results in the dropdown the value will not be set in the input. I suspect that the events are listening to a 'click' event instead of tab.

**Comment by jshimko** [comment]
You'll probably want to report that at the [upstream repo](https://github.com/ubilabs/geocomplete).  This is just a wrapper around that project with a few updates to the README for Meteor usage.

**Comment by braadworst** [comment]
My bad. Will do thanks

**Comment by bialesdaniel** [comment]
Has anyone found a solution to this? I tried the upsteam repo but didn't have any luck there

**Comment by jshimko** [comment]
@bialesdaniel, the upstream repo is the only place to go for problems with Geocomplete itself.  There are absolutely no modifications to the project in this package (and there never will be).  This package is just a wrapper for easy usage in Meteor apps.  

Have you filed an issue over there yet?  [This](https://github.com/ubilabs/geocomplete/issues/246) appears to be the only relevant issue, but I'm not sure if it's the same one you're having.

Sorry I don't have a better answer for you.
