### ISSUE TITLE
Alternative lists of results

### ISSUE THREAD

**Issue by aessig** [jshimko/meteor-geocomplete#27]
Hello.
Thank you so much for your work. It really works great. 
I was just wondering how I could make it work with Semantic UI and the search function. Simpler, would it be possible to extract request result to fill another list than the one used by default here ? Please let me know.

**Comment by jshimko** [comment]
This Meteor package is longer maintained. Please direct all questions to the official Geocomplete repo.

https://github.com/ubilabs/geocomplete
