### ISSUE TITLE
How to get result of input?

### ISSUE THREAD

**Issue by acomito** [jshimko/meteor-geocomplete#28]
I'd like to store the geocomplete result in a session variable or reactive var

the below strategies don't work...nothing is firing:

```
    'change #Location_Input': function (event, template) {

        console.log('change was fired');

    },
    'keyup #Location_Input': function (event, template) {

        console.log('keyup was fired');

    },
```

I see the below in the docs but there is no indication or where to put this:

```
$("input")
  .geocomplete()
  .bind("geocode:result", function(event, result){
    console.log(result);
  });
```

**Comment by jshimko** [comment]
You use that event listener once your component has rendered.

From the readme...

> To convert an input field into an autocompleting location search field, simply reactively call the Geocomplete plugin when your template is rendered and the Google Maps API is loaded:
> 
> ``` js
> Template.myTemplate.onRendered(function() {
>   this.autorun(function () {
>     if (GoogleMaps.loaded()) {
>       $("input").geocomplete();
>     }
>   });
> });
> ```

So using the example you mentioned...

``` js
Template.myTemplate.onRendered(function() {
  this.autorun(function () {
    if (GoogleMaps.loaded()) {
      $("input")
        .geocomplete()
        .bind("geocode:result", function(event, result) {
          console.log(result);
        });
    }
  });
});
```

Every time search results are updated in the field, that callback will fire.
