### ISSUE TITLE
Google is not defined

### ISSUE THREAD

**Issue by romanrdgz** [jshimko/meteor-geocomplete#3]
I'm getting the following error at Firebug, and the autocomplete is not working:

Exception from Tracker afterFlush function: google is not defined
.initGeocoder@http://localhost:3000/packages/jeremy_geocomplete.js?158b7ca96e177686ccb411194789c7d312ee75a7:202:7
.init@http://localhost:3000/packages/jeremy_geocomplete.js?158b7ca96e177686ccb411194789c7d312ee75a7:132:7
GeoComplete@http://localhost:3000/packages/jeremy_geocomplete.js?158b7ca96e177686ccb411194789c7d312ee75a7:124:5
$.fn.geocomplete/<@http://localhost:3000/packages/jeremy_geocomplete.js?158b7ca96e177686ccb411194789c7d312ee75a7:564:22
.each@http://localhost:3000/packages/jquery.js?dd8bac56f8fd3666d433d2285ae01e52597cc51a:417:14
jQuery.prototype.each@http://localhost:3000/packages/jquery.js?dd8bac56f8fd3666d433d2285ae01e52597cc51a:169:10
$.fn.geocomplete@http://localhost:3000/packages/jeremy_geocomplete.js?158b7ca96e177686ccb411194789c7d312ee75a7:560:1
Template.landing.rendered@http://localhost:3000/lib/landing.js?e6bb112e16293b122497906ccfb7c6b16f834cf4:18:5
Template.prototype.constructView/<@http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:3008:7
Blaze.View.prototype.onViewReady/fire/</<@http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1733:11
Blaze._withCurrentView@http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:2043:12
Blaze.View.prototype.onViewReady/fire/<@http://localhost:3000/packages/blaze.js?efa68f65e67544b5a05509804bf97e2c91ce75eb:1732:9
Tracker.flush@http://localhost:3000/packages/tracker.js?517c8fe8ed6408951a30941e64a5383a7174bcfa:448:11

meteor....b7370ec (línea 887)

My code is quite simple:
if(Meteor.isClient){
  Meteor.startup(function() {
    GoogleMaps.load({
      key: 'here_i_have_put_my_key',
      libraries: 'places' 
    });
  });

  // Set places autocomplete
  Template.landing.rendered = function(){
    $('section :input').val('').fancyInput()[0].focus(); // Making my input cute
    $('section :input').geocomplete(); // Error
  }
}

Any idea?

**Comment by jshimko** [comment]
It would be helpful if you could publish an example repo that reproduces this problem.  This unfortunately isn't enough info for me to see what's causing your issue.  Sorry.

**Comment by romanrdgz** [comment]
I'll try to reduce it to a small example and update ASAP

**Comment by victorbstan** [comment]
I've had this issue as well, I've restarted meteor and it got fixed, but perhaps there is something more interesting going on here...

**Comment by jshimko** [comment]
It might help to use the `GoogleMaps.loaded()` method to make sure the API is ready before you call Geocomplete.

``` js
Template.myTemplate.rendered = function() {
  Tracker.autorun(function () {
    if (GoogleMaps.loaded()) {
      $("input").geocomplete();
    }
  });
}
```

`GoogleMaps.loaded()` is reactive, so Tracker will run that code as soon as the ready state changes.

I've updated the README to recommend that as the default configuration.  You can see it used in the example [here](https://github.com/jshimko/meteor-geocomplete-example/blob/master/meteor-geocomplete-example.js) too.

**Comment by victorbstan** [comment]
@jshimko That solved my issue, I haven't seen it come up again since using `if (GoogleMaps.loaded()) {` Thanks!
