### ISSUE TITLE
MapOptions: Zoom not working

### ISSUE THREAD

**Issue by EmirGluhbegovic** [jshimko/meteor-geocomplete#31]
I have the following code:
if (GoogleMaps.loaded()) {
            $("input").geocomplete({ 
                details: "form",
                map:".map",
                mapOptions: {
                    zoom: 12,
                    zoomControl: false,
                    mapTypeControlOptions: {
                        mapTypeIds:"ROADMAP"
                    },
                    streetViewControl: false,
                },
                markerOptions: {
                    draggable: true
                }
            }).bind("geocode:mapdragged", function(event, latLng){

```
            console.log('Working if shown');

        });
    }
```

Everything is working besides the zoom property. I do not understand why.
Any suggestions would be most welcome.

**Comment by jshimko** [comment]
This package is just a wrapper to use the [Geocomplete](https://github.com/ubilabs/geocomplete) library with Meteor.  I didn't write Geocomplete, so I unfortunately can't offer much support here.  It sounds like Geocomplete is loading and working for you, so this package is doing what it's supposed to.  Your best bet for additional support would be to [file an issue at the main repo for Geocomplete](https://github.com/ubilabs/geocomplete/issues).
