### ISSUE TITLE
Get current map center

### ISSUE THREAD

**Issue by EmirGluhbegovic** [jshimko/meteor-geocomplete#32]
My apologies if this is an issue that is not dealt with here.

I am trying to retrieve the current map center with the following code.
The geocode:mapdragged is working, but the result is coming back as:

[Exception: TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context. at Function.remoteFunction (<anonymous>:3:14)]

``` javascript
if (GoogleMaps.loaded()) {
            $("input").geocomplete({ 
                details: "form",
                map:".map",
                mapOptions: {
                    zoom: 12,
                    zoomControl: true,
                    mapTypeControlOptions: {
                        mapTypeIds:"ROADMAP"
                    },
                    streetViewControl: false,
                },
                markerOptions: {
                    draggable: false
                }
            }).bind("geocode:mapdragged", function(event, result){

                console.log(result);

            });
        }
```

**Comment by jshimko** [comment]
Please file all usage related issues at the [upstream repo](https://github.com/ubilabs/geocomplete/issues).
