### ISSUE TITLE
Google Maps API error: ApiNotActivatedMapError

### ISSUE THREAD

**Issue by DurhamSmith** [jshimko/meteor-geocomplete#33]
I am currently trying to make use of this however I get the following error: 
Google Maps API error: ApiNotActivatedMapError

This is strange because when I try to data from an example api call

> https://maps.googleapis.com/maps/api/place/autocomplete/json?input=Vict&types=(cities)&language=pt_BR&key="MY KEY HERE"

it works fine.

I am using angular2 not blaze, could this be a problem?

My main.js

```
// client
Meteor.startup(function() {
  GoogleMaps.load({
    key: 'MY KEY HERE',
    libraries: 'places'  // also accepts an array if you need more than one
  });
});
```

my html (although even if I take out all this HTML I still get the same error)

```
<div class="half">
  <h4>Autocompletes Only</h4>
  <input id="place1" type="text" name="place" placeholder="Start typing...">
</div>

<script>
    if (GoogleMaps.loaded()) {
      $("#place1").geocomplete();
    }
</script>

```

Any help is appreciated.

**Comment by kevinkorte** [comment]
@DurhamSmith I know it's been a few months, but in case someone else stumbles upon this, make sure in your api console for whatever google account you're going to use, you also enable the Google Maps JavaScript API. That took care of this for me.

**Comment by jshimko** [comment]
This Meteor package is longer maintained. Please direct all questions to the official Geocomplete repo.

https://github.com/ubilabs/geocomplete
