### ISSUE TITLE
before submit event

### ISSUE THREAD

**Issue by leizard** [jshimko/meteor-geocomplete#35]
Hi, thank you for your package.
Is there any event that I can use to format my string before sending it to Google ? For example, when user type "307/35 street name", I want to search as "307 street name".
Thank you very much.

**Comment by jshimko** [comment]
Hi @leizard.  Glad you find it useful.  

However, this is just a wrapper package for usage with Meteor.  I didn't write the Geocomplete library.  For usage support, I recommend asking over at [the upstream repo](https://github.com/ubilabs/geocomplete).

You may also want to consider [installing this with npm](https://www.npmjs.com/package/geocomplete) now that Meteor supports that.  Then you'll always have the latest version directly from the upstream provider.  

``` sh
meteor npm install geocomplete --save
```

Sorry I don't have a better answer!

**Comment by leizard** [comment]
Thank you @jshimko for your support. I appreciate that :).
