### ISSUE TITLE
On enter button stop goecode from triggering

### ISSUE THREAD

**Issue by raza2022** [jshimko/meteor-geocomplete#37]
@jshimko Thanks for the great work and continuous maintaining it. My requirement is to trigger or find the geocomplete manually. because I am doing some extra field work behind the scene (that is not related). the real problem is i attached the event on enter key but it's not preventing event from triggering the `geocode:result` here is my code
`'keyup #map-autocomplete': function(e, t){
        if( e.which == 13 ){
            e.stopImmediatePropagation()
            callMapSubmit(t);
        }`
but it triggers the `geocode:result` as well.
i tried with `e.preventDefault()` and `stopPropagation` as well but no luck
for now i don't want to go beyond, i just need it will not trigger on enter key. any help will be greatly appreciated Thanks

**Comment by jshimko** [comment]
This Meteor package is longer maintained. Please direct all questions to the official Geocomplete repo.

https://github.com/ubilabs/geocomplete
