### ISSUE TITLE
I do not work the maps in the new version of Meteor

### ISSUE THREAD

**Issue by Marcelrama** [jshimko/meteor-geocomplete#38]
Creating a new project from scratch and following the steps to achieve google places together with the maps I have not managed to work alone I get the search box googleplaces but I do not get the vizualuzacion of the map, the only way that managed to visualize and everything works Is correctly using

[geocomplete](Https://github.com/jshimko/meteor-geocomplete-example)

Which works with a somewhat old version of meteor.

**Comment by jshimko** [comment]
This Meteor package is longer maintained.  Please direct all questions to the official Geocomplete repo.

https://github.com/ubilabs/geocomplete
