### ISSUE TITLE
InvalidValueError: setComponentRestrictions: not an Object

### ISSUE THREAD

**Issue by MichalW** [jshimko/meteor-geocomplete#39]
I have error when I run geocomplete():
```
Template.test.onRendered(function () {
    this.autorun(function () {
        if (GoogleMaps.loaded()) {
            $('input.js-search-location').geocomplete();
        }
    })
});
```
**InvalidValueError: setComponentRestrictions: not an Object**

Do you have any idea what is wrong?

**Comment by jshimko** [comment]
Please see [the note in the readme](https://github.com/jshimko/meteor-geocomplete).  I don't maintain Geocomplete and this is just a wrapper for Meteor.  It's also obsolete at this point.  Please install the package via npm and post any issues at the official Geocomplete repo.

https://github.com/ubilabs/geocomplete
